### ISSUE TITLE
Browser capibility (IE 8 etc...)

### ISSUE THREAD

**Issue by sheiun** [green32768749/portfolio#1]
Current not support noscript, but there is a noscript.scss.

noscript.scss

```scss
@import "libs/vars";
@import "libs/functions";
@import "libs/mixins";
@import "libs/vendor";
@import "libs/breakpoints";
@import "libs/html-grid";

/* Wrapper */

#wrapper {
  opacity: 1 !important;
}

/* Nav */

#nav {
  a {
    opacity: 1;

    &:before,
    &:after {
      display: none;
    }

    span {
      top: 0;
      opacity: 1;

      &:after {
        display: none;
      }
    }
  }
}

/* Main */

#main {
  background: none;
  box-shadow: none;

  > .panel {
    background: #ffffff;
    margin-bottom: 2em;

    &:last-child {
      margin-bottom: 0;
    }
  }
}
```
